### ISSUE TITLE
`Uncaught (in promise) TypeError: Cannot read property 'time' of undefined`

### ISSUE THREAD

**Issue by catthehacker** [nektro/mantle#71]
![image](https://user-images.githubusercontent.com/31106839/93335897-5d3e5300-f827-11ea-91e4-a9d91747b122.png)
`x-msg-pane.js`

**Comment by nektro** [comment]
Is this still a problem in https://github.com/nektro/mantle/releases/tag/v49-a2d6e3d ? This issue just got fixed in https://github.com/nektro/mantle/commit/9374299dd2f6fc32fec754c605bb1d46c1d99a17

**Comment by catthehacker** [comment]
![image](https://mantle.trademark.cat/api/etc/badges/version.svg)

I should probably upgrade then lol

**Comment by catthehacker** [comment]
Still getting that issue.

**Comment by nektro** [comment]
because your version says `v49` but still doesnt have the updated code: https://mantle.trademark.cat/chat/js/x/x-msg-pane.js

![image](https://user-images.githubusercontent.com/5464072/93400588-f6c03180-f834-11ea-8de6-f36c12d64a00.png)

**Comment by catthehacker** [comment]
Right, I should go to sleep. Now it's updated properly and it's fixed. Other issue I have is the date is not displayed.
![image](https://user-images.githubusercontent.com/31106839/93401876-973d4280-f883-11ea-9702-415aeac7c8ee.png)
